"""Validate MovingCameraShim against a known synthetic moving-UAV clip.

The clip is generated by
    uav_guidance/server_code_only/main_program/synth_clip_gen.py
and shipped to `tmp/synth_uav_clip.mp4` + `tmp/synth_uav_clip_gt.json`.
That sidecar carries the ground-truth `H_live -> K0` we applied per frame
AND the GT world-frame `(x, y)` of every drawn agent — which lets us
score `MovingCameraShim` on the metric that ACTUALLY matters downstream:
"does an agent's pixel position back-project to the same world (x, y)
that the GT says it has?"

Pass criteria (downstream-meaningful metric):
  - Per (frame, agent) world-frame error <= 0.5 m on >= 95 % of pairs
  - Max world-frame error <= 1.5 m
  - >= 1 `REANCHORED` event during the clip
  - no `FROZEN` outside the first frame

The 7x7 K0-corner grid RMS is logged as a diagnostic (it's dominated by
lever-arm amplification of small angular errors at the image corners,
which is irrelevant to downstream ContextVAE — agents live in the
central region) but does NOT gate the pass/fail.

Also checks the PixelMetricShim API contract is preserved on frame 0
(the unmoved keyframe): MovingCameraShim round-trip should match the
static PixelMetricShim round-trip to numerical precision.

Run:
    python tests/test_ego_motion_shim.py
Exits 0 on full pass, 1 on any failure. Auto-invokes synth_clip_gen.py
if the fixture is missing.
"""

import json
import subprocess
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
SWAP_DIR = REPO_ROOT / "uav_guidance" / "server_code_only" / "main_program"
MAP_PICKLE = REPO_ROOT / "data" / "levelx" / "map" / "inD_01.pkl"
SYNTH_GEN = SWAP_DIR / "synth_clip_gen.py"
SYNTH_MP4 = REPO_ROOT / "tmp" / "synth_uav_clip.mp4"
SYNTH_GT = REPO_ROOT / "tmp" / "synth_uav_clip_gt.json"

# main_program/ has no __init__.py.
sys.path.insert(0, str(SWAP_DIR))


# -- pass thresholds --
# World-frame error gate is the actual pass criterion: this is what the
# downstream ContextVAE sees. 0.5 m / 1.5 m brackets match the bbox-center
# noise of YOLOv8 on aerial imagery (a few pixels at ~6 px/m ~= ~0.5 m).
WORLD_ERR_PASS_M = 0.5
WORLD_ERR_PASS_PAIR_FRAC = 0.95
WORLD_ERR_CEILING_M = 1.5
# Corner-grid RMS is logged for diagnostics only — see module docstring.
DIAG_GRID_RMS_INFO_PX = 5.0
MIN_REANCHORS = 1


def _project_homog(H: np.ndarray, pts_2d: np.ndarray) -> np.ndarray:
    pts_2d = np.asarray(pts_2d, dtype=np.float64).reshape(-1, 2)
    homog = np.concatenate([pts_2d, np.ones((pts_2d.shape[0], 1))], axis=1)
    out = (H @ homog.T).T
    return out[:, :2] / out[:, 2:3]


def check_imports() -> bool:
    print("=== check_imports ===")
    try:
        from ego_motion_shim import MovingCameraShim
    except Exception as e:
        print(f"  import failed: {e!r}")
        return False
    missing = []
    for name in ("update_frame", "pixel_to_metric", "metric_to_pixel",
                 "pixels_to_metric", "metrics_to_pixel"):
        if not callable(getattr(MovingCameraShim, name, None)):
            missing.append(f"MovingCameraShim.{name}")
    for prop in ("H_live_to_K0", "last_status"):
        if not isinstance(getattr(MovingCameraShim, prop, None), property):
            missing.append(f"MovingCameraShim.{prop} (property)")
    if missing:
        for m in missing:
            print(f"  missing: {m}")
        return False
    print("  MovingCameraShim API surface OK")
    return True


def check_synth_clip_present() -> bool:
    print("=== check_synth_clip_present ===")
    if SYNTH_MP4.exists() and SYNTH_GT.exists():
        print(f"  found {SYNTH_MP4.relative_to(REPO_ROOT)}"
              f" ({SYNTH_MP4.stat().st_size // 1024} KiB)")
        print(f"  found {SYNTH_GT.relative_to(REPO_ROOT)}")
        return True
    print(f"  missing fixture, invoking {SYNTH_GEN.relative_to(REPO_ROOT)}")
    proc = subprocess.run(
        [sys.executable, str(SYNTH_GEN)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        print(f"  synth_clip_gen failed (rc={proc.returncode}):")
        print(proc.stdout[-1000:])
        print(proc.stderr[-1000:])
        return False
    return SYNTH_MP4.exists() and SYNTH_GT.exists()


def check_recovered_homography() -> bool:
    print("=== check_recovered_homography ===")
    import cv2  # not used elsewhere; keep the import local

    from ego_motion_shim import MovingCameraShim

    gt = json.loads(SYNTH_GT.read_text())
    n_frames = int(gt["n_frames"])
    H_k0, W_k0 = int(gt["k0_shape_hw"][0]), int(gt["k0_shape_hw"][1])
    gt_frames = gt["frames"]
    print(f"  clip: {n_frames} frames, K0 {W_k0}x{H_k0}")

    cap = cv2.VideoCapture(str(SYNTH_MP4))
    if not cap.isOpened():
        print(f"  cv2.VideoCapture could not open {SYNTH_MP4}")
        return False

    shim = MovingCameraShim(str(MAP_PICKLE))

    # 7x7 corner grid for diagnostic logging only.
    xs_diag = np.linspace(0, W_k0 - 1, 7)
    ys_diag = np.linspace(0, H_k0 - 1, 7)
    grid_K0_diag = np.array([(x, y) for y in ys_diag for x in xs_diag])

    statuses = []
    rms_per_frame_diag = []           # corner-grid RMS in px (diagnostic only)
    world_errs_all_pairs_m: list = []  # one entry per (frame, agent) pair

    for t in range(n_frames):
        ok, frame = cap.read()
        if not ok:
            print(f"  could not read frame {t}")
            cap.release()
            return False
        bboxes_ltwh = [a["ltwh_live"] for a in gt_frames[t]["agents"]]
        status = shim.update_frame(frame, mask_bboxes_ltwh=bboxes_ltwh)
        statuses.append(status)

        H_live_to_K0_gt = np.array(gt_frames[t]["H_live_to_K0"], dtype=np.float64)
        H_K0_to_live_gt = np.linalg.inv(H_live_to_K0_gt)

        if shim.H_live_to_K0 is None:
            rms_per_frame_diag.append(float("nan"))
            continue
        H_K0_to_live_est = np.linalg.inv(shim.H_live_to_K0)

        # Diagnostic: 7x7 grid RMS (lever-arm amplified at corners; logged only).
        proj_gt = _project_homog(H_K0_to_live_gt, grid_K0_diag)
        proj_est = _project_homog(H_K0_to_live_est, grid_K0_diag)
        rms_per_frame_diag.append(
            float(np.sqrt(((proj_gt - proj_est) ** 2).sum(axis=1).mean()))
        )

        # Pass criterion: world-frame error on each GT-overlaid agent.
        # The agent's live-pixel position is known (rendered by synth_clip_gen).
        # Round-trip live -> metric via the shim; compare to GT world (x, y).
        agents = gt_frames[t].get("agents", [])
        for a in agents:
            u_live, v_live = a["center_live"]
            try:
                x_m_est, y_m_est = shim.pixel_to_metric(u_live, v_live)
            except RuntimeError:
                world_errs_all_pairs_m.append(float("inf"))
                continue
            x_m_gt, y_m_gt = a["world"]
            world_errs_all_pairs_m.append(
                float(np.hypot(x_m_est - x_m_gt, y_m_est - y_m_gt))
            )

    cap.release()

    n_reanchored = sum(1 for s in statuses if s == "REANCHORED")
    frozen_after_first = [i for i, s in enumerate(statuses[1:], start=1) if s == "FROZEN"]
    rms_diag = np.array(rms_per_frame_diag)
    diag_finite = rms_diag[np.isfinite(rms_diag)]
    world_errs = np.array(world_errs_all_pairs_m)
    world_finite = world_errs[np.isfinite(world_errs)]

    print(f"  status hist: OK={statuses.count('OK')}  "
          f"REANCHORED={n_reanchored}  FROZEN={statuses.count('FROZEN')}")
    if diag_finite.size:
        print(f"  [diag] corner-grid RMS px: median={np.median(diag_finite):.3f}  "
              f"max={diag_finite.max():.3f}  (info-only)")
    if world_finite.size:
        frac_pass = float((world_finite <= WORLD_ERR_PASS_M).mean())
        print(f"  world-frame agent error (m): "
              f"median={np.median(world_finite):.3f}  "
              f"max={world_finite.max():.3f}  "
              f"frac <= {WORLD_ERR_PASS_M}m = {frac_pass:.3f}  "
              f"(N={world_finite.size} pairs)")
    else:
        print("  no agent pairs scored (empty agent list?)")
        frac_pass = 0.0

    ok = True
    if world_finite.size == 0:
        print("  FAIL: no world-frame error samples")
        ok = False
    else:
        if frac_pass < WORLD_ERR_PASS_PAIR_FRAC:
            print(f"  FAIL: only {frac_pass:.3f} of pairs have err <= "
                  f"{WORLD_ERR_PASS_M} m (target {WORLD_ERR_PASS_PAIR_FRAC})")
            ok = False
        if world_finite.max() > WORLD_ERR_CEILING_M:
            print(f"  FAIL: max world-frame error "
                  f"{world_finite.max():.3f} m > ceiling {WORLD_ERR_CEILING_M} m")
            ok = False
    if n_reanchored < MIN_REANCHORS:
        print(f"  FAIL: only {n_reanchored} REANCHORED event(s); want >= {MIN_REANCHORS}")
        ok = False
    if frozen_after_first:
        print(f"  FAIL: FROZEN at frames {frozen_after_first[:10]}... "
              f"({len(frozen_after_first)} total) beyond frame 0")
        ok = False
    return ok


def check_contract_compat() -> bool:
    """On the unmoved keyframe (frame 0), MovingCameraShim's round-trip
    must match PixelMetricShim's round-trip to numerical precision —
    proves the API-compatible composition is bit-equivalent in the
    stationary degenerate case."""
    print("=== check_contract_compat ===")
    import cv2

    from ego_motion_shim import MovingCameraShim
    from pixel_metric_shim import PixelMetricShim

    cap = cv2.VideoCapture(str(SYNTH_MP4))
    ok, frame0 = cap.read()
    cap.release()
    if not ok:
        print(f"  could not read frame 0 from {SYNTH_MP4}")
        return False

    moving = MovingCameraShim(str(MAP_PICKLE))
    moving.update_frame(frame0, mask_bboxes_ltwh=None)
    static = PixelMetricShim(str(MAP_PICKLE))

    # Reuse the row-0 inD agent pulled by tests/test_contextvae_swap.py.
    val_txt = REPO_ROOT / "data" / "levelx" / "val" / "inD_01.txt"
    first_row = next(
        (ln for ln in val_txt.read_text().splitlines() if ln.strip()), None
    )
    toks = first_row.split()
    xy = np.array([float(toks[2]), float(toks[3])], dtype=np.float64)

    u_s, v_s = static.metric_to_pixel(*xy)
    u_m, v_m = moving.metric_to_pixel(*xy)
    diff_fwd = float(np.hypot(u_s - u_m, v_s - v_m))
    print(f"  metric->pixel diff: {diff_fwd:.2e} px "
          f"(static ({u_s:.3f},{v_s:.3f}) vs moving ({u_m:.3f},{v_m:.3f}))")

    xy_s = static.pixel_to_metric(u_s, v_s)
    xy_m = moving.pixel_to_metric(u_m, v_m)
    diff_back = float(np.hypot(xy_s[0] - xy_m[0], xy_s[1] - xy_m[1]))
    print(f"  pixel->metric diff: {diff_back:.2e} m")

    if diff_fwd > 1e-9 or diff_back > 1e-9:
        print("  FAIL: MovingCameraShim @ K0 must equal PixelMetricShim numerically")
        return False
    return True


def main() -> int:
    checks = [
        check_imports,
        check_synth_clip_present,
        check_recovered_homography,
        check_contract_compat,
    ]
    results = [(c.__name__, c()) for c in checks]
    print()
    failures = [n for n, ok in results if not ok]
    if failures:
        print(f"FAIL ({len(failures)}/{len(checks)}): {', '.join(failures)}")
        return 1
    print(f"PASS ({len(checks)}/{len(checks)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
